[base]
    debug_mode="debug"
    time_location="Asia/Shanghai"

[log]
    log_level ="trace"
    [log.file_writer]
        on= true
        log_path = "./nice_base.inf.log"
        rotate_log_path = "./nice_base.inf.log"
        wf_log_path = "./nice_base.wf.log"
        rotate_wf_log_path = "./nice_base.wf.log"
    [log.console_writer]
        on = true
        color = true